/*
 * This source file was generated by the Gradle 'init' task
 */
package task_1_1_1;

import main.java.task_1_1_1.Car;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Car car1 = new Car();
        // asdasd;
        car1.speed = 2;
        car1.SetSpeed(100);
        System.out.println(new App().getGreeting());
    }

}
