/*
 * This source file was generated by the Gradle 'init' task
 */
package org.hashtable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HashtableTest {
    @Test void simpleTestOnCreationPutUpdate () {
        Hashtable<String, Integer> ht = new Hashtable<>();
        java.util.Hashtable<String,Integer> realHt = new java.util.Hashtable<>();
        ht.put("aaa", 111);
        realHt.put("aaa", 111);
        ht.put("bbb", 222);
        realHt.put("bbb", 222);
        assertEquals(realHt.toString(), ht.toString());
        realHt.clear();
        ht.clear();
    }

    @Test void rehashTest () {
        Hashtable<String, Integer> ht = new Hashtable<>();
        java.util.Hashtable<String,Integer> realHt = new java.util.Hashtable<>();
        for (int i = 0; i < 500; i++) {
            ht.put(Integer.toString(i), i);
            realHt.put(Integer.toString(i), i);
        }
        assertEquals(ht.entrySet(), realHt.entrySet());
    }

    @Test void equalsTest () {
        Hashtable<String, Integer> ht = new Hashtable<>();
        java.util.Hashtable<String,Integer> realHt = new java.util.Hashtable<>();
        for (int i = 0; i < 500; i++) {
            ht.put(Integer.toString(i), i);
            realHt.put(Integer.toString(i), i);
        }
        assert(ht.equals(realHt));
    }

    @Test void removeTest () {
        Hashtable<String, Integer> ht = new Hashtable<>();
        ht.put("aaa", 111);
        ht.put("aaa", 222);
        ht.remove("aaa");
        assert(ht.isEmpty());
    }
}
