/*
 * This source file was generated by the Gradle 'init' task
 */
package org.graph;

public class App {

    public static void main(String[] args) {
        org.graph.Graph graph = new org.graph.matrix.Adjency();
        // read file
        // from terminal receive command
        // make nodes
        // make edges
        // delete edges
        // delete nodes
        // write
        // exit
    }
}
