/*
 * This source file was generated by the Gradle 'init' task
 */
package org.graph;

import java.util.List;
import java.util.ArrayList;
import java.nio.file.*;
import java.nio.charset.*;
import java.io.*;

// import org.graph.incidence.Matrix;

public class App {

    public static void main(String[] args) {
        Graph graph = new AdjencyList();
        Path file = Paths.get("text.txt");
        Reader rd = new Reader();
        rd.readFromFile(file);
        //graph
        // graph.pr();
        // List<String> lasd = new ArrayList<String>();

        // lasd.add("sdsd");

        // System.out.println(lasd.getLast());
        // read file
        // from terminal receive command
        // make nodes
        // make edges
        // delete edges
        // delete nodes
        // write
        // exit
    }
}
