/*
 * This source file was generated by the Gradle 'init' task
 */
package org.graph;

import java.util.List;
import java.util.ArrayList;

// import org.graph.incidence.Matrix;

public class App {

    public static void main(String[] args) {
        org.graph.Graph graph = new AdjencyMatrix();
        graph.pr();
        List<String> lasd = new ArrayList<String>();

        lasd.add("sdsd");

        System.out.println(lasd.getLast());
        // read file
        // from terminal receive command
        // make nodes
        // make edges
        // delete edges
        // delete nodes
        // write
        // exit
    }
}
