/*
 * This source file was generated by the Gradle 'init' task
 */
package org.simplenumbers;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void Pasd() {
        assert(true);
    }
}
