/*
 * This source file was generated by the Gradle 'init' task
 */
package org.blackjack;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull("asd", "app should have a greeting");
    }
}
