/*
 * This source file was generated by the Gradle 'init' task
 */
package task_1_1_1;

import task_1_1_1.*;

import java.io.File;
import java.util.Scanner;
import java.util.Arrays;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void simpleArray() {
        //App classUnderTest = new App();
        int [] simple_array = {5, 4, 3, 2, 1};
        int [] clone_simple_array = simple_array.clone();
        HeapSort.sort(simple_array);
        Arrays.sort(clone_simple_array);
        assertArrayEquals(clone_simple_array, simple_array, "app can sort simple array");
    }

    @Test void bigReversedArray() {
        //App classUnderTest = new App();
        int right = 100000;
        int cnt = 0;
        int [] arr = new int[right*2+100];
        for (int i = right; i > right; --i) {
            arr[cnt++] = i;
        }

        Scanner sc = new Scanner(System.in);
        int [] clone_array = arr.clone();
        HeapSort.sort(arr);
        Arrays.sort(clone_array);
        assertArrayEquals(clone_array, arr, "app can sort simple array");
    }
}
