/*
 * This source file was generated by the Gradle 'init' task
 */
package org.blackjack;

public class App {

    public static void main(String[] args) {
        Receiver receiver = new Receiver();
        int num;
        Game game;

        if (args.length>=2) {
            game = new Game(args[1], receiver); // transfer abstract humans
        } else {
            game = new Game(receiver);
        }
        
        // menu (game) loop
        while(true) {
            System.out.println("\"1\" to start the new round, \"0\" to exit");
            num = receiver.collectIntFromCmd();
            if (num == 1) {
                game.startRound();
            } else if (num == 0) {
                break;
            } else {
                System.out.println("Writed wrong number");
            }
        }
        receiver.closeReceiver();
    }
}
